### ISSUE TITLE
Many items missing in csljson

### ISSUE THREAD

**Issue by richardkaplan** [retorquere/devonthink#4]
If I view the biblatex output in my browser and then change it to csljson, there are many fewer items- why might that be?

**Comment by retorquere** [comment]
Can you upgrade BBT to 5.1.106 and plug the csljson url into your browser, changing `.csljson` to `.bc03b4fe-436d-4a1f-ba59-de4d2d7a63f7`? Does that show more items?

**Comment by richardkaplan** [comment]
Will try in about 30 min and let you know - thanks


________________________________

**Comment by retorquere** [comment]
NM -- translators must apparently explicitly tell Zotero they want subcollections. The stock CSL-JSON translator doesn't do it either. If you pick up BBT 5.1.107 it should be fixed.

**Comment by richardkaplan** [comment]
> bc03b4fe-436d-4a1f-ba59-de4d2d7a63f7

When I do that the format changes in the browser but I do not get additional citations.  It is still not bringing in any of the citations from child collections.

**Comment by retorquere** [comment]
Yeah the stock CSL JSON translator (`bc03b4fe-436d-4a1f-ba59-de4d2d7a63f7`) doesn't inform Zotero it wants subcollections either. Try .107 and the `.csljson` extension.

**Comment by richardkaplan** [comment]
I tried .107 

Once again the subcollection articles are present in the .biblatex output - but they are not present in the .csljson output

**Comment by retorquere** [comment]
Please check whether the changes from #2 make any difference for this issue, the exporter in use has changed.

**Comment by richardkaplan** [comment]
The changes from #2 work perfectly as far as including all of the articles and setting them up in folders

However the URLs and abstracts are blank.  I also do not see that information in the .json.   Can we bring those fields back?

**Comment by retorquere** [comment]
Post the JSON somewhere (slack, gist) and I can take a look.

**Comment by richardkaplan** [comment]
Correction... the raw .json appears to have all of my articles

However many of my collections are missing from the output.  Is seems to have processed the collections alphabetically and only got up to F.  Many collections/items in the .json never got included in the output.

**Comment by retorquere** [comment]
`url` is now lowercase, `abstract` is now `abstractNote`.

**Comment by retorquere** [comment]
I can't see in your library, so I can't interpret "many".

If you pick any single missing collection, where does it live in relation to the collection you are exporting?

**Comment by richardkaplan** [comment]
My collections are pretty well distributed in the alphabet as far as starting letter and randomly sorted.  The Output colllections are aphabetized but only make it from A to F; G to Z are missing.

**Comment by retorquere** [comment]
That's fine, just pick any one. If we have a concrete problem to discuss we can zoom in easier.

**Comment by richardkaplan** [comment]
(1) I changed to url and abstractNOte as you suggested - abstracts now do appear (thank you).  URLs are still missing

(2) A missing category in the output is called Intriguing

**Comment by retorquere** [comment]
(1) I see plenty of items with an URL. Have you lowercased it in the template?

(2) I'll look at the JSON to see why it's not being laid out on disk. The "Intriguing" collection is present in the JSON.

WRT alphabetization, you mean as it's laid out on disk? I don't control how MacOS sorts files/folders.

**Comment by richardkaplan** [comment]
This is my template

![image](https://user-images.githubusercontent.com/6059733/61259278-7f31d680-a747-11e9-947d-79576be6de5d.png)

But here it is missing in the resulting html:

![image](https://user-images.githubusercontent.com/6059733/61259300-953f9700-a747-11e9-8b90-4777a6bfa03e.png)

**Comment by richardkaplan** [comment]
With regard to alphabetization, these are the folders created on my Desktop - the ones A-F are there.  The ones in the json not starting with A-F are missing

![image](https://user-images.githubusercontent.com/6059733/61259396-f7000100-a747-11e9-89ea-884ba718d1ee.png)

**Comment by retorquere** [comment]
When I run the script on your JSON, I get

```
ENAMETOOLONG: name too long
```
somewhere after `Epidural Steroid Injections Import Test`

**Comment by retorquere** [comment]
> This is my template

This is separate from items going missing though. Can you open a new issue for this?

**Comment by richardkaplan** [comment]
I will rename that category and see if it fixes it - hold on

**Comment by retorquere** [comment]
I've added a `maxlength` parameter to the config file, names will be cut to that length.

**Comment by retorquere** [comment]
(for the time being, can you start the script from the command line? otherwise you'll miss errors it displays)

**Comment by retorquere** [comment]
no need to rename, the error was most likely the length of an article title, not the collection.

**Comment by richardkaplan** [comment]
I renamed Epidural Steroid Injections Import Test to start with ZZZ.  Then I got many more collections until Statins; it stopped there.  

So there must be another long title in the Statins collection.

Presumably your new maxlength will fix that - thanks

**Comment by richardkaplan** [comment]
Maybe a coincidence but url now works too!

**Comment by retorquere** [comment]
must be a coincidence.
